name: deploy-release

on:
  push:
    branches: [ release-* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"
          git config --local user.name "${GITHUB_ACTOR}"

      - name: Configure Git user
        run: git fetch origin gh-pages --depth=1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - id: get-tag
        run: |
          tag=$(echo ${{ steps.extract_branch.outputs.branch }} | cut -d- -f2)
          echo "::set-output name=tag::$tag"
      - run: echo "${{steps.get-tag.outputs.tag}}"

      - name: Deploy with mike ðŸš€
        run: mike deploy --push ${{ steps.extract_branch.outputs.branch }} -t '${{steps.get-tag.outputs.tag}}'